apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: HEAD
    path: environments/prod
    directory:
      recurse: true
      exclude: 'root-app.yaml'
  destination:
    server: https://kubernetes.default.svc # Prod 클러스터 URL
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
