apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/boxty123/argocd-demo.git
    targetRevision: HEAD
    path: demo-app/charts/demo-app
    helm:
      valueFiles:
      - ../../environments/prod/values/product.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
